@base_url = http://dev-laravel.sjahn.gtz.kr


###
# banners
GET {{base_url}}/api/banners
Content-Type: application/json

{
    "category_id": 1
}

###
# auth.create
POST {{base_url}}/api/auth/register
Content-Type: application/json

{
    "email": "abc123@abc.com",
    "name": "dante",
    "password": "1234"
}


###
# auth.login
# @name login
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "email": "abc123@abc.com",
    "password": "1234"
}


###
@access_token = {{login.response.body.access_token}}


###
# auth.me
GET {{base_url}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{access_token}}