@base_url = http://dev-sjahn.gtz.kr


###
# banners
GET {{base_url}}/api/banners
Content-Type: application/json

{
    "category_id": 1
}

###
# user.create
POST {{base_url}}/api/user/register
Content-Type: application/json

{
    "email": "ahnsb214@gmail.com",
    "name": "dante",
    "password": "022617aa"
}


###
# @name login
POST {{base_url}}/api/user/login
Content-Type: application/json

{
    "email": "asj214@naver.com",
    "password": "022617aa"
}

# @access_token = {{login.response.body.access_token}}



###
# api/user/me
GET {{base_url}}/api/user/me
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kZXYtc2phaG4uZ3R6LmtyXC9hcGlcL3VzZXJcL2xvZ2luIiwiaWF0IjoxNjA1MzA3NDc1LCJleHAiOjE2MDUzMTEwNzUsIm5iZiI6MTYwNTMwNzQ3NSwianRpIjoiMVEzM3hOMzFETzlsanpsViIsInN1YiI6MSwicHJ2IjoiODdlMGFmMWVmOWZkMTU4MTJmZGVjOTcxNTNhMTRlMGIwNDc1NDZhYSJ9.qnKGiyOC4rQpn6veDRu5tMLA32qWfRjL08J24EFc7ic